Try using a VERSION file instead of release.yaml

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -4,9 +4,6 @@ on:
   push:
     branches: [release]
 
-env:
-  version: 0.5.2
-
 jobs:
   docker-build:
     runs-on: ubuntu-latest
@@ -15,6 +12,18 @@ jobs:
 
     steps:
       - uses: actions/checkout@v2
+      - name: Read version number
+        run: echo "version"=$(cat VERSION) > $GITHUB_ENV
+      - uses: actions-ecosystem/action-regex-match@v2
+        id: version
+        with:
+          text: ${{ env.version }}
+          regex: '\d+\.\d+\.\d+'
+      - name: Check valid version
+        if: steps.version.outputs.match == ''
+        run: |
+          echo "Invalid version: ${{ env.version }}"
+          exit 1
       - name: Set up QEMU
         uses: docker/setup-qemu-action@v1
         with:
